# -*- coding: utf-8 -*-
"""pydantic-AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0V-o56adcaaDwA3dKlA0QnKNGSCixZP
"""

pip install pydantic-ai

"""user question
-> Pydantic AI Agent -> Instructions -> Tools -> Dependencies -> Output Schema -> LLM -> Structured Pydantic Response


"""

from pydantic import BaseModel

class MathOutput(BaseModel):
    answer: str

from pydantic import BaseModel
from pydantic_ai import Agent

class MathOutput(BaseModel):
    answer: str

math_agent = Agent(
    "openai:gpt-4o-mini",
    instructions="You are a math assistant. Always use tools for arithmetic calculations.",
    output_type=MathOutput,
)

@math_agent.tool_plain
def multiply(a: int, b: int) -> int:
    """Multiply two numbers."""
    return a * b

result = await math_agent.run("What is 8 multiplied by 9?")
print(result.output)

from pydantic import BaseModel

from pydantic_ai import Agent

class CityLocation(BaseModel):
  city:str
  country: str

agent = Agent('openai:gpt-4o-mini', output_type=CityLocation)
result = await agent.run('Where was the olympics in 2012')
print(result.output)
print(result.usage())

from dataclasses import dataclass
import asyncio
import httpx

from pydantic_ai import Agent, RunContext


@dataclass
class MyDeps:
    api_key: str
    http_client: httpx.AsyncClient


agent = Agent(
    'openai:gpt-4o-mini',
    deps_type=MyDeps,
)


@agent.system_prompt
async def get_system_prompt(ctx: RunContext[MyDeps]) -> str:
    return "You are a funny assistant."


@agent.tool
async def get_joke_material(ctx: RunContext[MyDeps], subject: str) -> str:
    return f"Here is some joke material about {subject}: it is unexpectedly dramatic."


async def main():
    async with httpx.AsyncClient() as client:
        deps = MyDeps('foobar', client)
        result = await agent.run('Tell me a joke about math.', deps=deps)
        print(result.output)

await main()

"""dependencies"""

from dataclasses import dataclass
import asyncio
import httpx

from pydantic_ai import Agent, RunContext


@dataclass
class MyDeps:
    api_key: str
    http_client: httpx.AsyncClient


agent = Agent(
    'openai:gpt-4o-mini',
    deps_type=MyDeps,
)


@agent.system_prompt
async def get_system_prompt(ctx: RunContext[MyDeps]) -> str:
    return "You are a funny assistant."


@agent.tool
async def get_joke_material(ctx: RunContext[MyDeps], subject: str) -> str:
    return f"Here is some joke material about {subject}: it is unexpectedly dramatic."


async def main():
    async with httpx.AsyncClient() as client:
        deps = MyDeps('foobar', client)
        result = await agent.run('Tell me a joke about math.', deps=deps)
        print(result.output)


await main()

import sqlite3
from dataclasses import dataclass
from pydantic import BaseModel
import logfire
from pydantic_ai import Agent, RunContext

logfire.configure(send_to_logfire='if-token-present')
logfire.instrument_pydantic_ai()

@dataclass
class DatabaseConn:
    sqlite_conn: sqlite3.Connection

    async def customer_name(self, *, id: int) -> str | None:
        res = self.sqlite_conn.execute(
            "SELECT name FROM customers WHERE id=?", (id,)
        )
        row = res.fetchone()
        if row:
            return row[0]
        return None

    async def customer_balance(self, *, id: int) -> float:
        res = self.sqlite_conn.execute(
            "SELECT balance FROM customers WHERE id=?", (id,)
        )
        row = res.fetchone()
        if row:
            return row[0]
        raise ValueError("Customer not found")


@dataclass
class SupportDependencies:
    customer_id: int
    db: DatabaseConn


class SupportOutput(BaseModel):
    support_advice: str
    block_card: bool
    risk: int


support_agent = Agent(
    "openai:gpt-5.2",
    deps_type=SupportDependencies,
    output_type=SupportOutput,
    instructions=(
        "You are a support agent in our bank. Give the customer support "
        "and judge the risk level of their query. Reply using the customer's name."
    ),
)


@support_agent.instructions
async def add_customer_name(ctx: RunContext[SupportDependencies]) -> str:
    customer_name = await ctx.deps.db.customer_name(id=ctx.deps.customer_id)
    return f"The customer's name is {customer_name!r}"


@support_agent.tool
async def customer_balance(ctx: RunContext[SupportDependencies]) -> str:
    balance = await ctx.deps.db.customer_balance(id=ctx.deps.customer_id)
    return f"${balance:.2f}"


if __name__ == "__main__":
    with sqlite3.connect(":memory:") as con:
        con.execute("CREATE TABLE customers(id, name, balance)")
        con.execute("INSERT INTO customers VALUES (123, 'John', 123.45)")
        con.commit()

        deps = SupportDependencies(
            customer_id=123,
            db=DatabaseConn(sqlite_conn=con),
        )

        result = await support_agent.run("What is my balance?", deps=deps)
        print(result.output)

        result = await support_agent.run("I just lost my card!", deps=deps)
        print(result.output)