# -*- coding: utf-8 -*-
"""subagents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IjnYO7gpe4WFDecZGvBJpkYCzuXlKiDr
"""

from google.colab import userdata
import os

api_key = userdata.get('OPENAI_API_KEY')
os.environ['OPENAI_API_KEY'] = api_key

!pip install langchain-openai

import os
from google.colab import userdata

os.environ['LANGSMITH_TRACING'] = 'true'
os.environ['LANGSMITH_ENDPOINT'] = 'https://eu.api.smith.langchain.com'
os.environ['LANGSMITH_API_KEY'] = userdata.get('LANGSMITH_API_KEY')
os.environ['LANGSMITH_PROJECT'] = "new"
os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY')

from langchain.tools import tool
from langchain.agents import create_agent
from langsmith import traceable, wrappers
from openai import OpenAI
from google.colab import userdata
import os


api_key = userdata.get('OPENAI_API_KEY')
os.environ['OPENAI_API_KEY'] = api_key
client = wrappers.wrap_openai(OpenAI(api_key=api_key))


os.environ['LANGSMITH_TRACING'] = 'true'
os.environ['LANGSMITH_ENDPOINT'] = 'https://eu.api.smith.langchain.com'
os.environ['LANGSMITH_API_KEY'] = userdata.get('LANGSMITH_API_KEY')
os.environ['LANGSMITH_PROJECT'] = "new"
os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY')

research_agent = create_agent(
    model="gpt-4.1",
    system_prompt="You are a research specialist..."
)


writer_agent = create_agent(
    model="gpt-4.1",
    system_prompt="You are a writing specialist......"
)

SUBAGENTS = {
    "research": research_agent,
    "writer" : writer_agent
}
@traceable(name="subagent_run")
def run_subagent(agent_name:str, description:str) -> str:
  agent = SUBAGENTS[agent_name]

  result = agent.invoke(
      {
          "messages" : [
              {"role": "user", "content": description}
          ]
      }
  )
  return result["messages"][-1].content

@tool
def task(agent_name: str, description: str) -> str:
  """
      Delegate tasks to subagents.

    agent_name options:
    - "research" → factual queries
    - "writer" → content generation

    description: task to perform
      """
  return run_subagent(agent_name, description)


main_agent = create_agent(
    model="gpt-4.1",
    tools=[task],
    system_prompt=(
      "You are a coordinator of specialized sub-agents.\n\n"

    "You MUST NOT answer directly.\n"
    "You MUST ALWAYS use the task tool.\n\n"

    "Rules:\n"
    "- For factual queries → use agent_name='research'\n"
    "- For writing → use agent_name='writer'\n\n"

    "Always call:\n"
    "task(agent_name='...', description='...')\n\n"

    "Never respond without using the tool."
    ),
)

@traceable(name="main_run")
def run():
    return main_agent.invoke({
        "messages": [{"role": "user", "content": "Tell me about AI"}]
    })

result = run()
print(result["messages"][-1].content)

